### ISSUE TITLE
Question about the Calculator

### ISSUE THREAD

**Issue by Yukieiros** [tewky/dvcalculator#3]
I'm confused about the Veteran Mode what qualifies a pokemon as a Veteran?

**Comment by AndyJ01** [comment]
Hey, I am not the maintainer, but I can answer this. More info is also available a few places on the internet if you dig for it a bit.
It means that the stat experience must be maxed to 65535 in every stat. This way, there is only one possible DV for every in-game stat number as long as the pokemon is at least level 50. In most cases though, you will be easily level 100 by the time you max these because it takes ~1000ish battles to get there. Vitamins only get you to about 20000 and cannot be used to grow higher than that.
- Andy

Sent from Yahoo Mail on Android 
 
  On Mon, May 15, 2023 at 3:10 PM, ***@***.***> wrote:   


I'm confused about the Veteran Mode what qualifies a pokemon as a Veteran?
